### PR TITLE
migrate the jenkins pipeline to the Buildkite

### PR DESCRIPTION
**Pull request by sharbuz**
## What does this PR do?

Migration of the pipeline from Jenkins to the Buildkite

## Checklist

- [x] Lint
- [x] Linux tests
- [x] Windows tests
- [-] Mac tests (waiting for the agent)

## Related issues

-

### CODE REVIEW

**Comment by jlind23** [comment]
buildkite test it

**Review by mrodm — COMMENTED** [review]
LGTM

Just missing to add the environment variable required to add comments in Pull Requests in the catalog-info.yaml, as Jenkins does here https://github.com/elastic/elastic-agent-autodiscover/blob/main/catalog-info.yaml#L49

Example of this configuration: https://github.com/elastic/elastic-package/blob/8a9596724648197abad7bb931362995f6a63c11a/catalog-info.yaml#L56-L57

**Comment by sharbuz** [comment]
@mrodm , I've added the status messages to the PR, please check it once again

**Comment by sharbuz** [comment]
If it's fine for now, please merge this PR, because I don't have permissions for that :(

**Pull request merged**
