### PR TITLE
Update docker dependency

### PR DESCRIPTION
**Pull request by michalpristas**
Updated dependency is needed for agent. 
Replaced deprecated type `type.ContainerListOptions` with `container.ListOptions`

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]

**Comment by jlind23** [comment]
@pazone the build is failing as the Windows VM are using 1.20 whereas they should now be using Go 1.21, could you please help us out here?
cc @rowlandgeoff

**Comment by ycombinator** [comment]
@michalpristas Looks like this PR would close out https://github.com/elastic/elastic-agent-autodiscover/issues/91?

**Comment by rowlandgeoff** [comment]
Looks like the Go version is specified here: https://github.com/elastic/elastic-agent-autodiscover/blob/main/.buildkite/pipeline.yml#L5

Updating that is probably the quickest fix, though I think that we try to preinstall Go on most of the images as well (possibly a future improvement to look at).

**Comment by jlind23** [comment]
Thanks @rowlandgeoff, I'll try to bump it here - https://github.com/elastic/elastic-agent-autodiscover/pull/101

**Pull request merged**
